name = "roots"
description = "Simple and secure theme"
license = "MIT"
homepage = "https://github.com/red-roots/roots"
min_version = "0.17.0"
demo = "https://juice.huhu.io"

[extra]

[author]
name = "Huhu teams"
homepage = "https://huhu.io"
